# lookup tables for soccer

premier_league_team_lts = {
   "AFC Bournemouth":"/soccer/team/_/id/349/afc-bournemouth",
   "Arsenal":"/soccer/team/_/id/359/arsenal",
   "Aston Villa":"/soccer/team/_/id/362/aston-villa",
   "Brentford":"/soccer/team/_/id/337/brentford",
   "Brighton & Hove Albion":"/soccer/team/_/id/331/brighton-hove-albion",
   "Chelsea":"/soccer/team/_/id/363/chelsea",
   "Crystal Palace":"/soccer/team/_/id/384/crystal-palace",
   "Everton":"/soccer/team/_/id/368/everton",
   "Fulham":"/soccer/team/_/id/370/fulham",
   "Leeds United":"/soccer/team/_/id/357/leeds-united",
   "Leicester City":"/soccer/team/_/id/375/leicester-city",
   "Liverpool":"/soccer/team/_/id/364/liverpool",
   "Manchester City":"/soccer/team/_/id/382/manchester-city",
   "Manchester United":"/soccer/team/_/id/360/manchester-united",
   "Newcastle United":"/soccer/team/_/id/361/newcastle-united",
   "Nottingham Forest":"/soccer/team/_/id/393/nottingham-forest",
   "Southampton":"/soccer/team/_/id/376/southampton",
   "Tottenham Hotspur":"/soccer/team/_/id/367/tottenham-hotspur",
   "West Ham United":"/soccer/team/_/id/371/west-ham-united",
   "Wolverhampton Wanderers":"/soccer/team/_/id/380/wolverhampton-wanderers",
}

premier_league_stats_lts = {
   "AFC Bournemouth":"/soccer/team/stats/_/id/349",
   "Arsenal":"/soccer/team/stats/_/id/359",
   "Aston Villa":"/soccer/team/stats/_/id/362",
   "Brentford":"/soccer/team/stats/_/id/337",
   "Brighton & Hove Albion":"/soccer/team/stats/_/id/331",
   "Chelsea":"/soccer/team/stats/_/id/363",
   "Crystal Palace":"/soccer/team/stats/_/id/384",
   "Everton":"/soccer/team/stats/_/id/368",
   "Fulham":"/soccer/team/stats/_/id/370",
   "Leeds United":"/soccer/team/stats/_/id/357",
   "Leicester City":"/soccer/team/stats/_/id/375",
   "Liverpool":"/soccer/team/stats/_/id/364",
   "Manchester City":"/soccer/team/stats/_/id/382",
   "Manchester United":"/soccer/team/stats/_/id/360",
   "Newcastle United":"/soccer/team/stats/_/id/361",
   "Nottingham Forest":"/soccer/team/stats/_/id/393",
   "Southampton":"/soccer/team/stats/_/id/376",
   "Tottenham Hotspur":"/soccer/team/stats/_/id/367",
   "West Ham United":"/soccer/team/stats/_/id/371",
   "Wolverhampton Wanderers":"/soccer/team/stats/_/id/380",
}

premier_league_roster_lts = {
   "AFC Bournemouth":"/soccer/team/squad/_/id/349/eng.bournemouth",
   "Arsenal":"/soccer/team/squad/_/id/359/eng.arsenal",
   "Aston Villa":"/soccer/team/squad/_/id/362/eng.aston_villa",
   "Brentford":"/soccer/team/squad/_/id/337/eng.brentford",
   "Brighton & Hove Albion":"/soccer/team/squad/_/id/331/eng.brighton_hove_albion",
   "Chelsea":"/soccer/team/squad/_/id/363/eng.chelsea",
   "Crystal Palace":"/soccer/team/squad/_/id/384/eng.crystal_palace",
   "Everton":"/soccer/team/squad/_/id/368/eng.everton",
   "Fulham":"/soccer/team/squad/_/id/370/eng.fulham",
   "Leeds United":"/soccer/team/squad/_/id/357/eng.leeds_united",
   "Leicester City":"/soccer/team/squad/_/id/375/eng.leicester_city",
   "Liverpool":"/soccer/team/squad/_/id/364/eng.liverpool",
   "Manchester City":"/soccer/team/squad/_/id/382/eng.manchester_city",
   "Manchester United":"/soccer/team/squad/_/id/360/eng.manchester_united",
   "Newcastle United":"/soccer/team/squad/_/id/361/eng.newcastle_united",
   "Nottingham Forest":"/soccer/team/squad/_/id/393/eng.nottingham_orest",
   "Southampton":"/soccer/team/squad/_/id/376/eng.southampton",
   "Tottenham Hotspur":"/soccer/team/squad/_/id/367/eng.tottenham_hotspur",
   "West Ham United":"/soccer/team/squad/_/id/371/eng.west_ham",
   "Wolverhampton Wanderers":"/soccer/team/squad/_/id/380/eng.wolverhampton",
}

ucl_team_lts = {
   "AC Milan":"/soccer/team/_/id/103/ac-milan",
   "Ajax Amsterdam":"/soccer/team/_/id/139/ajax-amsterdam",
   "Atletico Madrid":"/soccer/team/_/id/1068/atletico-madrid",
   "Barcelona":"/soccer/team/_/id/83/barcelona",
   "Bayer Leverkusen":"/soccer/team/_/id/131/bayer-leverkusen",
   "Bayern Munich":"/soccer/team/_/id/132/bayern-munich",
   "Benfica":"/soccer/team/_/id/1929/benfica",
   "Borussia Dortmund":"/soccer/team/_/id/124/borussia-dortmund",
   "Celtic":"/soccer/team/_/id/256/celtic",
   "Chelsea":"/soccer/team/_/id/363/chelsea",
   "Club Brugge":"/soccer/team/_/id/570/club-brugge",
   "Dinamo Zagreb":"/soccer/team/_/id/597/dinamo-zagreb",
   "Eintracht Frankfurt":"/soccer/team/_/id/125/eintracht-frankfurt",
   "FC Copenhagen":"/soccer/team/_/id/909/fc-copenhagen",
   "FC Porto":"/soccer/team/_/id/437/fc-porto",
   "FC Salzburg":"/soccer/team/_/id/2790/fc-salzburg",
   "Internazionale":"/soccer/team/_/id/110/internazionale",
   "Juventus":"/soccer/team/_/id/111/juventus",
   "Liverpool":"/soccer/team/_/id/364/liverpool",
   "Maccabi Haifa":"/soccer/team/_/id/611/maccabi-haifa",
   "Manchester City":"/soccer/team/_/id/382/manchester-city",
   "Marseille":"/soccer/team/_/id/176/marseille",
   "Napoli":"/soccer/team/_/id/114/napoli",
   "Paris Saint-Germain":"/soccer/team/_/id/160/paris-saint-germain",
   "RB Leipzig":"/soccer/team/_/id/11420/rb-leipzig",
   "Rangers":"/soccer/team/_/id/257/rangers",
   "Real Madrid":"/soccer/team/_/id/86/real-madrid",
   "Sevilla":"/soccer/team/_/id/243/sevilla",
   "Shakhtar Donetsk":"/soccer/team/_/id/493/shakhtar-donetsk",
   "Sporting CP":"/soccer/team/_/id/2250/sporting-cp",
   "Tottenham Hotspur":"/soccer/team/_/id/367/tottenham-hotspur",
   "Viktoria Plzen":"/soccer/team/_/id/11706/viktoria-plzen"
}

ucl_stats_lts = {
   "AC Milan":"/soccer/team/stats/_/id/103/ac-milan",
   "Ajax Amsterdam":"/soccer/team/stats/_/id/139/ajax-amsterdam",
   "Atletico Madrid":"/soccer/team/stats/_/id/1068/atletico-madrid",
   "Barcelona":"/soccer/team/stats/_/id/83/barcelona",
   "Bayer Leverkusen":"/soccer/team/stats/_/id/131/bayer-leverkusen",
   "Bayern Munich":"/soccer/team/stats/_/id/132/bayern-munich",
   "Benfica":"/soccer/team/stats/_/id/1929/benfica",
   "Borussia Dortmund":"/soccer/team/stats/_/id/124/borussia-dortmund",
   "Celtic":"/soccer/team/stats/_/id/256/celtic",
   "Chelsea":"/soccer/team/stats/_/id/363/chelsea",
   "Club Brugge":"/soccer/team/stats/_/id/570/club-brugge",
   "Dinamo Zagreb":"/soccer/team/stats/_/id/597/dinamo-zagreb",
   "Eintracht Frankfurt":"/soccer/team/stats/_/id/125/eintracht-frankfurt",
   "FC Copenhagen":"/soccer/team/stats/_/id/909/fc-copenhagen",
   "FC Porto":"/soccer/team/stats/_/id/437/fc-porto",
   "FC Salzburg":"/soccer/team/stats/_/id/2790/fc-salzburg",
   "Internazionale":"/soccer/team/stats/_/id/110/internazionale",
   "Juventus":"/soccer/team/stats/_/id/111/juventus",
   "Liverpool":"/soccer/team/stats/_/id/364/liverpool",
   "Maccabi Haifa":"/soccer/team/stats/_/id/611/maccabi-haifa",
   "Manchester City":"/soccer/team/stats/_/id/382/manchester-city",
   "Marseille":"/soccer/team/stats/_/id/176/marseille",
   "Napoli":"/soccer/team/stats/_/id/114/napoli",
   "Paris Saint-Germain":"/soccer/team/stats/_/id/160/paris-saint-germain",
   "RB Leipzig":"/soccer/team/stats/_/id/11420/rb-leipzig",
   "Rangers":"/soccer/team/stats/_/id/257/rangers",
   "Real Madrid":"/soccer/team/stats/_/id/86/real-madrid",
   "Sevilla":"/soccer/team/stats/_/id/243/sevilla",
   "Shakhtar Donetsk":"/soccer/team/stats/_/id/493/shakhtar-donetsk",
   "Sporting CP":"/soccer/team/stats/_/id/2250/sporting-cp",
   "Tottenham Hotspur":"/soccer/team/stats/_/id/367/tottenham-hotspur",
   "Viktoria Plzen":"/soccer/team/stats/_/id/11706/viktoria-plzen"
}

ucl_roster_lts = {
    "AC Milan": "/soccer/team/_/id/103/ita.ac-milan",
    "Ajax Amsterdam": "/soccer/team/_/id/139/ned.ajax-amsterdam",
    "Atletico Madrid": "/soccer/team/_/id/1068/esp.atletico-madrid",
    "Barcelona": "/soccer/team/_/id/83/esp.barcelona",
    "Bayer Leverkusen": "/soccer/team/_/id/131/ger.bayer-leverkusen",
    "Bayern Munich": "/soccer/team/_/id/132/ger.bayern-munich",
    "Benfica": "/soccer/team/_/id/1929/por.benfica",
    "Borussia Dortmund": "/soccer/team/_/id/124/ger.borussia-dortmund",
    "Chelsea": "/soccer/team/_/id/363/eng.chelsea",
    "Dinamo Zagreb": "/soccer/team/_/id/597/rus.dinamo-zagreb",
    "Eintracht Frankfurt": "/soccer/team/_/id/125/ger.eintracht-frankfurt",
    "FC Porto": "/soccer/team/_/id/437/por.fc-porto",
    "FC Salzburg": "/soccer/team/_/id/2790/ger.fc-salzburg",
    "Internazionale": "/soccer/team/_/id/110/ita.internazionale",
    "Juventus": "/soccer/team/_/id/111/ita.juventus",
    "Liverpool": "/soccer/team/_/id/364/eng.liverpool",
    "Manchester City": "/soccer/team/_/id/382/eng.manchester-city",
    "Marseille": "/soccer/team/_/id/176/fra.marseille",
    "Napoli": "/soccer/team/_/id/114/ita.napoli",
    "Paris Saint-Germain": "/soccer/team/_/id/160/fra.paris-saint-germain",
    "RB Leipzig": "/soccer/team/_/id/11420/ger.rb-leipzig",
    "Real Madrid": "/soccer/team/_/id/86/esp.real-madrid",
    "Sevilla": "/soccer/team/_/id/243/esp.sevilla",
    "Sporting CP": "/soccer/team/_/id/2250/por.sporting-cp",
    "Tottenham Hotspur": "/soccer/team/_/id/367/eng.tottenham-hotspur"
}
